version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.15
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: echo npm version
          command: npm -v
      - run:
          name: Install npm
          command: npm install
      - run:
          name: check test1.js lint
          command: npm run lint1
      - run:
          name: check test2.js lint
          command: npm run lint2
      - run:
          name: check test3.js lint
          command: npm run lint3
